name: Update Schemas and Presets

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/schema-update.yml"
      - "packages/action-schema-update/*"
      - "baselines/*"
      - "presets/*"
      - "schemas/*"
  workflow_dispatch:

concurrency: schema-update

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::022327457572:role/kitten-science-us0-maintainer
          role-session-name: GitHubActions

      - name: Deploy to S3
        run: |
          aws s3 sync ./schemas/working-draft s3://kitten-science-us0/schemas/working-draft \
            --cache-control "public, s-maxage=60, maxage=60" \
            --content-type "application/schema+json" \
            --delete
          aws s3 sync ./baselines s3://kitten-science-us0/baselines --delete \
            --cache-control "public, s-maxage=60, maxage=60" \
            --delete
          aws s3 sync ./presets s3://kitten-science-us0/presets --delete \
            --cache-control "public, s-maxage=60, maxage=60" \
            --delete
